// Copyright (C) 2026 Fiber
//
// All rights reserved. This script, including its code and logic, is the
// exclusive property of Fiber. Redistribution, reproduction,
// or modification of any part of this script is strictly prohibited
// without prior written permission from Fiber.
//
// Conditions of use:
// - The code may not be copied, duplicated, or used, in whole or in part,
//   for any purpose without explicit authorization.
// - Redistribution of this code, with or without modification, is not
//   permitted unless expressly agreed upon by Fiber.
// - The name "Fiber" and any associated branding, logos, or
//   trademarks may not be used to endorse or promote derived products
//   or services without prior written approval.
//
// Disclaimer:
// THIS SCRIPT AND ITS CODE ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. IN NO EVENT SHALL
// FIBER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO LOSS OF USE,
// DATA, PROFITS, OR BUSINESS INTERRUPTION) ARISING OUT OF OR RELATED TO THE USE
// OR INABILITY TO USE THIS SCRIPT, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// Unauthorized copying or reproduction of this script, in whole or in part,
// is a violation of applicable intellectual property laws and will result
// in legal action.

// ignore_for_file: constant_identifier_names

/// {@template auth_gen}
/// Annotation used to declare a fully-defined authentication configuration
/// for automatic code generation within the Fiber ecosystem.
///
/// When applied to a class, this annotation instructs the generator to:
/// - Bind authentication logic to a specific Firestore collection.
/// - Configure the Cloud Functions regional endpoint.
/// - Apply password validation rules.
/// - Generate sign-in and sign-up flows based on the provided modules.
/// - Produce strongly-typed authentication services and helpers.
///
/// The annotated class acts purely as a declarative configuration entry
/// point and typically contains no implementation details.
///
/// ### Example
/// ```dart
/// @AuthGen(
///   firestoreCollection: "__fbs__users",
///   region: FirebaseFunctionsRegion.us_central1,
///   passwordPolicy: PasswordPolicy(
///     min: 8,
///     requireUppercase: true,
///     requireDigits: true,
///   ),
///   signIn: SignInModule(
///     requireEmailVerification: true,
///   ),
///   signUp: SignUpModule(
///     requireEmailVerification: false,
///     autoSignInAfterSignUp: true,
///   ),
/// )
/// class UserAuthConfig {}
/// ```
///
/// The generator may then produce:
/// - Firestore-bound user repositories.
/// - Region-configured HTTPS callable integrations.
/// - Password validation logic.
/// - Sign-in and sign-up handlers respecting module options.
/// - Typed authentication services and guards.
///
/// ### Notes
/// - [firestoreCollection] specifies the associated user collection.
/// - [region] determines the Cloud Functions deployment region.
/// - [passwordPolicy] defines validation rules applied during registration.
/// - [signIn] configures login behavior.
/// - [signUp] configures account creation behavior.
/// - The annotated class serves only as a generation entry point.
/// {@endtemplate}
class AuthGen {
  /// Defines the Firestore collection used as the primary user store
  /// for this authentication domain.
  ///
  /// All authentication-related data generated by this configuration
  /// will be scoped to this collection.
  ///
  /// This typically includes:
  /// - User profile documents
  /// - Role or permission metadata
  /// - Authentication state flags
  /// - Device/session-related metadata (if generated)
  ///
  /// Example:
  /// ```dart
  /// firestoreCollection: "__fbs__users"
  /// ```
  ///
  /// The generator uses this value to:
  /// - Bind authentication services to a specific Firestore path
  /// - Generate strongly-typed document references
  /// - Scope read/write helpers to the correct collection
  /// - Align backend callable logic with the correct user store
  final String firestoreCollection;

  /// Defines the Cloud Functions region used for all generated
  /// authentication-related HTTPS callable operations.
  ///
  /// This region determines which deployment location is targeted
  /// when invoking backend authentication logic.
  ///
  /// Example:
  /// ```dart
  /// region: FirebaseFunctionsRegion.us_central1
  /// ```
  ///
  /// The generator uses this value to:
  /// - Configure region-aware callable clients
  /// - Align frontend calls with the deployed backend region
  /// - Prevent cross-region invocation inconsistencies
  /// - Ensure deterministic endpoint resolution at compile-time
  final FirebaseFunctionsRegion region;

  /// Defines the password validation rules applied during
  /// account creation.
  ///
  /// These rules are enforced in the generated authentication
  /// flow and may also be mirrored in backend validation logic.
  ///
  /// Example:
  /// ```dart
  /// passwordPolicy: PasswordPolicy(
  ///   min: 8,
  ///   requireUppercase: true,
  ///   requireDigits: true,
  /// )
  /// ```
  ///
  /// The generator may use this configuration to:
  /// - Validate passwords before invoking backend callables
  /// - Generate consistent client/server validation logic
  /// - Produce strongly-typed password guards
  final PasswordPolicy passwordPolicy;

  /// Configures the behavior of the generated sign-in flow.
  ///
  /// This module controls login-related constraints such as
  /// whether email verification is required before authentication
  /// is considered valid.
  ///
  /// The generator may use this configuration to:
  /// - Enforce email verification checks after authentication
  /// - Generate guarded sign-in helpers
  /// - Produce role-aware authentication guards
  final SignInModule signIn;

  /// Configures the behavior of the generated sign-up flow.
  ///
  /// This module defines how account creation behaves,
  /// including whether email verification is required and
  /// whether the user is automatically signed in after registration.
  ///
  /// The generator may use this configuration to:
  /// - Generate registration handlers
  /// - Control post-registration session behavior
  /// - Enforce verification flows before granting access
  final SignUpModule signUp;

  /// {@macro auth_gen}
  const AuthGen({
    this.firestoreCollection = "users",
    this.region = FirebaseFunctionsRegion.us_central1,
    this.passwordPolicy = const PasswordPolicy(),
    this.signIn = const SignInModule(),
    this.signUp = const SignUpModule(),
  });
}

/// {@template sign_in_module}
/// Configuration module defining the behavior of the generated
/// sign-in flow.
///
/// This module controls login-related security constraints,
/// such as whether a user must have a verified email address
/// before the authentication process is considered valid.
///
/// The generator may use this configuration to:
/// - Enforce email verification checks after authentication
/// - Generate guarded sign-in helpers
/// - Block access to protected resources if verification fails
/// - Produce role-aware session validation logic
/// {@endtemplate}
class SignInModule {
  /// {@macro sign_in_module}
  ///
  /// Indicates whether email verification is required
  /// before a successful sign-in is accepted.
  ///
  /// If `true`, the generated authentication logic may:
  /// - Reject unverified users after authentication
  /// - Trigger verification reminders
  /// - Prevent session activation until verification succeeds
  ///
  /// Defaults to `true`.
  final bool requireEmailVerification;

  /// {@macro sign_in_module}
  const SignInModule({this.requireEmailVerification = true});
}

/// {@template sign_up_module}
/// Configuration module defining the behavior of the generated
/// sign-up (account creation) flow.
///
/// This module controls registration-related security and
/// post-creation behavior.
///
/// The generator may use this configuration to:
/// - Enforce email verification during or after registration
/// - Control automatic session creation after account creation
/// - Generate guarded onboarding flows
/// - Produce verification-aware registration handlers
/// {@endtemplate}
class SignUpModule {
  /// {@macro sign_up_module}
  ///
  /// Indicates whether email verification is required
  /// before the account is considered fully active.
  ///
  /// If `true`, the generated logic may:
  /// - Restrict access to protected resources
  /// - Require verification before enabling session features
  ///
  /// Defaults to `false`.
  final bool requireEmailVerification;

  /// {@macro sign_up_module}
  ///
  /// Determines whether the user should be automatically
  /// signed in immediately after successful registration.
  ///
  /// If `true`, the generator may:
  /// - Create and activate a session automatically
  /// - Skip manual login after sign-up
  ///
  /// If `false`, the user must explicitly sign in
  /// after account creation.
  ///
  /// Defaults to `true`.
  final bool autoSignInAfterSignUp;

  /// {@macro sign_up_module}
  const SignUpModule({this.requireEmailVerification = false, this.autoSignInAfterSignUp = true});
}

/// {@template password_policy}
/// Defines the password validation rules applied during
/// account creation.
///
/// This policy controls structural constraints such as
/// length requirements and character composition rules.
///
/// The generator may use this configuration to:
/// - Validate passwords before invoking backend callables
/// - Generate consistent client-side and server-side validation
/// - Produce password strength guards
/// - Enforce deterministic registration constraints
/// {@endtemplate}
class PasswordPolicy {
  /// {@macro password_policy}
  ///
  /// Minimum allowed password length.
  ///
  /// Defaults to `6`.
  final int min;

  /// {@macro password_policy}
  ///
  /// Optional maximum allowed password length.
  ///
  /// If `null`, no upper bound is enforced.
  final int? max;

  /// {@macro password_policy}
  ///
  /// Indicates whether at least one uppercase character
  /// (A–Z) is required.
  ///
  /// Defaults to `false`.
  final bool requireUppercase;

  /// {@macro password_policy}
  ///
  /// Indicates whether at least one lowercase character
  /// (a–z) is required.
  ///
  /// Defaults to `false`.
  final bool requireLowercase;

  /// {@macro password_policy}
  ///
  /// Indicates whether at least one numeric digit (0–9)
  /// is required.
  ///
  /// Defaults to `false`.
  final bool requireDigits;

  /// {@macro password_policy}
  ///
  /// Indicates whether at least one special character
  /// must be included.
  ///
  /// Defaults to `false`.
  final bool requireSpecialChars;

  /// {@macro password_policy}
  const PasswordPolicy({
    this.min = 6,
    this.max,
    this.requireUppercase = false,
    this.requireLowercase = false,
    this.requireDigits = false,
    this.requireSpecialChars = false,
  });
}

/// {@template firebase_functions_region}
/// Enumerates all supported deployment regions for
/// Firebase Cloud Functions (2nd generation).
///
/// Each value represents a Google Cloud region where
/// authentication-related HTTPS callable functions
/// may be deployed.
///
/// The selected region determines:
/// - The physical location of backend execution
/// - Network latency characteristics
/// - Regulatory/data residency alignment
/// - Cross-region invocation behavior
///
/// The generator uses this enum to:
/// - Produce region-aware callable clients
/// - Prevent invalid region strings at compile-time
/// - Ensure deterministic backend targeting
/// {@endtemplate}
enum FirebaseFunctionsRegion {
  /// {@macro firebase_functions_region}
  us_central1("us-central1"),

  /// {@macro firebase_functions_region}
  us_east1("us-east1"),

  /// {@macro firebase_functions_region}
  us_east4("us-east4"),

  /// {@macro firebase_functions_region}
  us_west1("us-west1"),

  /// {@macro firebase_functions_region}
  us_west2("us-west2"),

  /// {@macro firebase_functions_region}
  us_west3("us-west3"),

  /// {@macro firebase_functions_region}
  us_west4("us-west4"),

  /// {@macro firebase_functions_region}
  northamerica_northeast1("northamerica-northeast1"),

  /// {@macro firebase_functions_region}
  northamerica_northeast2("northamerica-northeast2"),

  /// {@macro firebase_functions_region}
  southamerica_east1("southamerica-east1"),

  /// {@macro firebase_functions_region}
  southamerica_west1("southamerica-west1"),

  /// {@macro firebase_functions_region}
  europe_west1("europe-west1"),

  /// {@macro firebase_functions_region}
  europe_west2("europe-west2"),

  /// {@macro firebase_functions_region}
  europe_west3("europe-west3"),

  /// {@macro firebase_functions_region}
  europe_west4("europe-west4"),

  /// {@macro firebase_functions_region}
  europe_west6("europe-west6"),

  /// {@macro firebase_functions_region}
  europe_west8("europe-west8"),

  /// {@macro firebase_functions_region}
  europe_west9("europe-west9"),

  /// {@macro firebase_functions_region}
  europe_west10("europe-west10"),

  /// {@macro firebase_functions_region}
  europe_west12("europe-west12"),

  /// {@macro firebase_functions_region}
  europe_central2("europe-central2"),

  /// {@macro firebase_functions_region}
  europe_north1("europe-north1"),

  /// {@macro firebase_functions_region}
  europe_southwest1("europe-southwest1"),

  /// {@macro firebase_functions_region}
  me_central1("me-central1"),

  /// {@macro firebase_functions_region}
  me_west1("me-west1"),

  /// {@macro firebase_functions_region}
  africa_south1("africa-south1"),

  /// {@macro firebase_functions_region}
  asia_east1("asia-east1"),

  /// {@macro firebase_functions_region}
  asia_east2("asia-east2"),

  /// {@macro firebase_functions_region}
  asia_northeast1("asia-northeast1"),

  /// {@macro firebase_functions_region}
  asia_northeast2("asia-northeast2"),

  /// {@macro firebase_functions_region}
  asia_northeast3("asia-northeast3"),

  /// {@macro firebase_functions_region}
  asia_south1("asia-south1"),

  /// {@macro firebase_functions_region}
  asia_south2("asia-south2"),

  /// {@macro firebase_functions_region}
  asia_southeast1("asia-southeast1"),

  /// {@macro firebase_functions_region}
  asia_southeast2("asia-southeast2"),

  /// {@macro firebase_functions_region}
  australia_southeast1("australia-southeast1"),

  /// {@macro firebase_functions_region}
  australia_southeast2("australia-southeast2");

  /// The canonical region identifier used by Firebase/Google Cloud.
  final String value;

  const FirebaseFunctionsRegion(this.value);
}
